config/routes.rb
Rails.application.routes.draw do

  put '/update_styles/:id' => 'styles#update', as: 'update_styles'
  root 'styles#change_styles'

end

app/models/style.rb
class Style < ActiveRecord::Base
  serialize :properties, Hash

  def header_color
    self["properties"]["header_color"]
  end

  def header_color=(val)
    self["properties"]["header_color"] = val
  end

  def footer_color
    self["properties"]["footer_color"]
  end

  def footer_color=(val)
    self["properties"]["footer_color"] = val
  end

  def font_family
    self["properties"]["font_family"]
  end

  def font_family=(val)
    self["properties"]["font_family"] = val
  end

  def title
    self["properties"]["title"]
  end

  def title=(val)
    self["properties"]["title"] = val
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

  def change_styles
    if Style.first.nil?
      @style = Style.create
    else
      @style = Style.first
    end
    respond_to do |format|
      format.html { render :change_styles }
    end
  end

  def update
    @style = Style.find(params[:id])
    @style.update(style_params)
    respond_to do |format|
      format.js
    end
  end

  private
    def style_params
      params.require(:style).permit(:header_color, :footer_color, :font_family, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/styles_helper.rb
module StylesHelper
  def build_options
    [ ["Select one option", ""],
      ["Open Sans", "'Open Sans', sans-serif"],
      ["Roboto", "'Roboto', sans-serif"],
      ["Slabo", "'Slabo 27px', serif"],
      ["Lato", "'Lato', sans-serif"],
      ["Oswald", "'Oswald', sans-serif"]
    ]
  end

  def font_family_options
    options_for_select(build_options)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Traveltripper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:700|Roboto:300|Slabo+27px|Lato:700italic|Oswald:700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">Travel Tripper</a>
      </div>
      <div class="navbar-collapse collapse" id="navbar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  <footer class="footer">
    <div class="container">
      <p class="text-muted">
        Single page website with option to change page header and footer colors and font on the page except for controls.
        Also changes the title of the page.
      </p>
    </div>
  </footer>
</body>
</html>

app/views/styles/_form.html.erb
<%= form_for @style, url: update_styles_path(@style), method: :put, :html => { :class => "form-horizontal style" }, :remote => true do |f| %>

  <div class="form-group">
    <%= f.label :header_color, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :header_color, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :footer_color, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :footer_color, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :font_family, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :font_family, font_family_options, :selected_key => f.object.font_family, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/styles/change_styles.html.erb
<%- model_class = Style -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.change_styles', 'Change %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

<script type="text/javascript">
  $(document).ready(function(){
    var properties = <%= @style.properties.to_json.html_safe%>;
    $(document).change_styles(properties);
  });
</script>

app/views/styles/update.js.erb
var properties = <%= @style.properties.to_json.html_safe%>;
$(document).change_styles(properties);